### ISSUE TITLE
error in installing

### ISSUE THREAD

**Issue by desperado39** [MaayanLab/maayanlab-bioinformatics#5]
i am installing in windows 10 but it shows the error.
![Capture1](https://user-images.githubusercontent.com/42930300/149080402-cad2d3ad-2904-4226-8118-b9265e28b547.PNG)

**Comment by u8sand** [comment]
This seems to be an issue with your git installation. Information online found by searching for `error setting certificate verify locations` suggests it might be fixed by running the command:

```bash
set GIT_SSL_NO_VERYIFY=true
```
in the same terminal prior to executing `pip install`

or by running
```bash
git config --global http.sslverify "false"
```
to configure git globally to disable ssl verification.
